update cd to deploy to vm

diff --git a/.github/workflows/cd_http-server.yaml b/.github/workflows/cd_http-server.yaml
--- a/.github/workflows/cd_http-server.yaml
+++ b/.github/workflows/cd_http-server.yaml
@@ -7,11 +7,11 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout the code to machine
-        uses: actions/checkout@v2
+        uses: actions/checkout@v4
       - name: Login to DockerHub
         uses: docker/login-action@v3
         with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          username: ${{ vars.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
@@ -27,4 +27,14 @@ jobs:
           tags: tsmukesh51/dpl-dockr-http:${{ github.sha }},tsmukesh51/dpl-dockr-http:latest
           cache-to: type=gha,mode=max
       - name: Deploy on VM
-        run: 'echo "hello world"'
+        run: |
+          mkdir -p ~/.ssh
+          echo "${{ vars.VULTR_MYTRYING_FINGERPRINT }}" &> ~/.ssh/known_hosts
+          echo "${{ secrets.SDWMUKESH_SSH_PRIVKEY }}" &> ~/.ssh/ssh_key
+          chmod 600 ~/.ssh/ssh_key
+          ssh -i ~/.ssh/ssh_key root@${{ vars.VULTR_MYTRYING_IPADD }} << EOF
+          docker pull tsmukesh51/dpl-dockr-http:${{ github.sha }} || { echo "Pull failed"; exit 1; }
+          docker stop tsmukesh51/dpl-dockr-http || true
+          docker rm tsmukesh51/dpl-dockr-http || true
+          docker -e DATABASE_URL="${{ NT_DATABASE_URL }}" -p 3000:3000 -d --name tsmukesh51-dpl-dockr-http:${{ github.sha }} || { echo "Run failed"; exit 1; }
+          EOF
