update cd to check ipv6 issue

diff --git a/.github/workflows/cd_http-server.yaml b/.github/workflows/cd_http-server.yaml
--- a/.github/workflows/cd_http-server.yaml
+++ b/.github/workflows/cd_http-server.yaml
@@ -32,9 +32,10 @@ jobs:
           echo "${{ vars.VULTR_MYTRYING_FINGERPRINT }}" &> ~/.ssh/known_hosts
           echo "${{ secrets.SDWMUKESH_SSH_PRIVKEY }}" &> ~/.ssh/ssh_key
           chmod 600 ~/.ssh/ssh_key
-          ssh -i ~/.ssh/ssh_key root@${{ vars.VULTR_MYTRYING_IPADD }} << EOF
+          ping6 2001:19f0:5401:0956:5400:05ff:fe90:5181
+          ssh -i ~/.ssh/ssh_key -6 root@${{ vars.VULTR_MYTRYING_IPADD }} << EOF
           docker pull tsmukesh51/dpl-dockr-http:${{ github.sha }} || { echo "Pull failed"; exit 1; }
           docker stop tsmukesh51/dpl-dockr-http || true
           docker rm tsmukesh51/dpl-dockr-http || true
-          docker -e DATABASE_URL="${{ secrets.NT_DATABASE_URL }}" -p 3000:3000 -d --name tsmukesh51-dpl-dockr-http:${{ github.sha }} || { echo "Run failed"; exit 1; }
+          docker run -e DATABASE_URL="${{ secrets.NT_DATABASE_URL }}" -p 3000:3000 -d --name tsmukesh51-dpl-dockr-http:${{ github.sha }} || { echo "Run failed"; exit 1; }
           EOF
