update cd files

diff --git a/.github/workflows/cd_ws-server.yaml b/.github/workflows/cd_ws-server.yaml
--- a/.github/workflows/cd_ws-server.yaml
+++ b/.github/workflows/cd_ws-server.yaml
@@ -1,13 +1,13 @@
-name: Deploy the http-server
+name: Deploy the ws-server
 on:
   push:
     branches: [master]
     paths:
       - "dpl-dockr/**"
       - "!dpl-dockr/apps/web/**"
-      - "!dpl-dockr/apps/ws-server/**"
+      - "!dpl-dockr/apps/http-server/**"
       - "!dpl-dockr/dockerfile/web.dockerfile"
-      - "!dpl-dockr/dockerfile/ws-server.dockerfile"
+      - "!dpl-dockr/dockerfile/http-server.dockerfile"
 jobs:
   build:
     runs-on: ubuntu-latest
@@ -22,30 +22,32 @@ jobs:
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
       - name: Pull Image from DockerHub
-        run: docker pull tsmukesh51/dpl-dockr-http:latest || true
+        run: docker pull tsmukesh51/dpl-dockr-ws:latest || true
       - name: Build and Push to DockerHub
         uses: docker/build-push-action@v6
         with:
           context: ./dpl-dockr
-          file: ./dpl-dockr/dockerfile/http-server.dockerfile
+          file: ./dpl-dockr/dockerfile/web.dockerfile
           push: true
-          cache-from: type=registry,ref=tsmukesh51/dpl-dockr-http:latest
-          tags: tsmukesh51/dpl-dockr-http:${{ github.sha }},tsmukesh51/dpl-dockr-http:latest
+          cache-from: type=registry,ref=tsmukesh51/dpl-dockr-ws:latest
+          tags: tsmukesh51/dpl-dockr-ws:${{ github.sha }},tsmukesh51/dpl-dockr-ws:latest
           cache-to: type=gha,mode=max
+          build-args: |
+            DATABASE_URL="${{ secrets.NT_DATABASE_URL }}"
       - name: Deploy on VM
         run: |
           mkdir -p ~/.ssh
-          echo "${{ vars.VULTR_MYTRYING_FINGERPRINT }}" &> ~/.ssh/known_hosts
+          ssh-keyscan "${{ vars.VULTR_MYTRYING_FINGERPRINT }}" &> ~/.ssh/known_hosts
           echo "${{ secrets.SDWMUKESH_SSH_PRIVKEY }}" &> ~/.ssh/ssh_key
           chmod 600 ~/.ssh/ssh_key
           ssh -i ~/.ssh/ssh_key root@${{ vars.VULTR_MYTRYING_IPADD }} << EOF
           echo "Pulling image"
-          docker pull tsmukesh51/dpl-dockr-http:${{ github.sha }} || { echo "Pull failed"; exit 1; }
+          docker pull tsmukesh51/dpl-dockr-ws:${{ github.sha }} || { echo "Pull failed"; exit 1; }
           echo "Container Stopped"
-          docker stop tsmukesh51/dpl-dockr-http || true
+          docker stop tsmukesh51/dpl-dockr-ws || true
           echo "Container Removed"
-          docker stop $(docker ps | grep "tsmukesh51/dpl-dockr-http" | awk '{ print $1 }') || true
-          docker rm $(docker ps -a | grep "tsmukesh51/dpl-dockr-http" | awk '{ print $1 }') || true
+          docker stop $(docker ps | grep "tsmukesh51/dpl-dockr-ws" | awk '{ print $1 }') || true
+          docker rm $(docker ps -a | grep "tsmukesh51/dpl-dockr-ws" | awk '{ print $1 }') || true
           echo "Running New Container"
-          docker run -e DATABASE_URL="${{ secrets.NT_DATABASE_URL }}" -p 3000:3000 -d tsmukesh51/dpl-dockr-http:${{ github.sha }} || { echo "Run failed"; exit 1; }
+          docker run -e DATABASE_URL="${{ secrets.NT_DATABASE_URL }}" -p 3000:3000 -d tsmukesh51/dpl-dockr-ws:${{ github.sha }} || { echo "Run failed"; exit 1; }
           EOF
